[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[functions]
  external_node_modules = ["@supabase/supabase-js", "openai", "stripe", "playwright-core"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  PLAYWRIGHT_BROWSERS_PATH = "0"